GET http://localhost:5000/tester
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRmFyaWQiLCJpYXQiOjE2NjcxOTU1ODIsImV4cCI6MTY2NzI4MTk4Mn0.j3mbJgEaRg3cnghD16qPhfBmHq1Al4HuZ0Mn86cjHv8

###

POST http://localhost:5000/test
Content-Type: application/json

{
    "username": "Farid"
}


###


POST http://localhost:5000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRmFyaWQiLCJpYXQiOjE2NjcxOTU0NTV9.IVVTREk0fY9F18BFqVxnvmEpaswx0IRvaL5g5k4zVLQ"
}