GET http://localhost:5000/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTY2NzIwMzQ5MCwiZXhwIjoxNjY3MjAzNTAwfQ.Lg1jqvUDpjuYS-ZWldxVnss2ff2lwnZk_z_Dxrfyog8
###


POST http://localhost:5000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTY2NzIwMzM3OX0.xuXYUrQPyvGTIaIiVW71-67RXHARqyu9zt-jqRNMjiY"
}

###

POST http://localhost:5000/test
Content-Type: application/json

{
    "username": "test"
}


###

