GET http://localhost:5000/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTY2NzIwMzQ5MCwiZXhwIjoxNjY3MjAzNTAwfQ.Lg1jqvUDpjuYS-ZWldxVnss2ff2lwnZk_z_Dxrfyog8
###


POST http://localhost:5000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTY2NzIwMzM3OX0.xuXYUrQPyvGTIaIiVW71-67RXHARqyu9zt-jqRNMjiY"
}

###

POST http://localhost:5000/test
Content-Type: application/json

{
    "username": "test"
}


###

GET http://localhost:6000/login

###
POST http://localhost:6000/dashboard
Content-Type: application/json

{
    "username":"Tester",
    "password":"abc123"
}

###
GET http://localhost:6000/logout

###
GET http://localhost:6000/boom




###
GET http://localhost:5000/

###
POST http://localhost:5000/dashboard
Content-Type: application/json

{
    "uid" : "211",
    "password" : "F@rid207"
}

###
GET http://localhost:5000/moh-list

###
GET http://localhost:5000/user_register

###
POST http://localhost:5000/success

###
POST https://clientstg.fmx.asia/token

{
    "userNameOrEmailAddress" : "glba0001",
    "password" : "J02B4VcU",
    "grant_type" : "password"
}